spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8760/eureka/
