spring:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8766

spring.cloud.config.server.git.uri: https://github.com/wangyubing/pmscloud.git
#spring.cloud.config.server.git.searchPaths: respo
#spring.cloud.config.label: master
#spring.cloud.config.server.git.username: 12
#spring.cloud.config.server.git.password: 12344

#spring.rabbitmq.host: localhost
#spring.rabbitmq.port: 5672
#spring.rabbitmq.username: ”√ªß√˚
#spring.rabbitmq.password: √‹¬Î